apiversion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    app: my-app
    type: frontend
spec:
  selector:
    matchlabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        env: production
    spec:
     containers:
      - name: nginx
        image: nginx
  