{
 "title": "Dummy Data Transaction Metrics",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "Total Transaction Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dummy_data",
     "rawSql": "SELECT\n  COUNT(*),\n  startDate AS time\nFROM\n  dummy_data.grafdisplay\nWHERE $__timeFilter(startDate)\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Total Transaction Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "dummy_data",
     "rawSql": "SELECT\n  COUNT(*),\n  startDate AS time\nFROM\n  dummy_data.grafdisplay\nWHERE $__timeFilter(startDate)\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Total Transaction Success Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dummy_data",
     "rawSql": "SELECT\n  COUNT(*),\n  startDate AS time\nFROM\n  dummy_data.grafdisplay\nWHERE $__timeFilter(startDate) AND responseCode = 0\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Top 10 Successful Institutions (Per Volume)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS `FAILED TRANSACTIONS`,\n  bankName\nFROM\n  dummy_data.grafdisplay\nWHERE\n  $__timeFilter(startDate) AND responseCode = 0\nGROUP BY\n  bankName\nORDER BY\n  `FAILED TRANSACTIONS` DESC;\n"
    }
   ]
  },
  {
   "title": "Transaction Failure Reason(s)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dummy_data",
     "rawSql": "SELECT\n  distinct COUNT(response),\n  response\n  -- startDate AS time\nFROM\n  dummy_data.grafdisplay\nWHERE $__timeFilter(startDate) AND responseCode != 0\nGROUP BY\n  response\n-- ORDER BY\n--   response DESC"
    }
   ]
  },
  {
   "title": "Total Transaction Failure Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dummy_data",
     "rawSql": "SELECT\n  COUNT(*),\n  startDate AS time\nFROM\n  dummy_data.grafdisplay\nWHERE $__timeFilter(startDate) AND responseCode != 0\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Top 10 Failing Institutions (Per Volume)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS `FAILED TRANSACTIONS`,\n  bankName\nFROM\n  dummy_data.grafdisplay\nWHERE\n  $__timeFilter(startDate) AND responseCode != 0\nGROUP BY\n  bankName\nORDER BY\n  `FAILED TRANSACTIONS` DESC;\n"
    }
   ]
  }
 ]
}